### ISSUE TITLE
NoClassDefFoundError scala/reflect/api/TypeCreator

### ISSUE THREAD

**Issue by sake92** [scalameta/sbt-scalafmt#104]
This issue was reported here: https://github.com/sake92/hepek-starter/issues/4  

<details>
  <summary>Whole stacktrace</summary>
sbt:root> last Compile / scalafmt
[debug] Change report:
[debug]         Checked: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Modified: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Unmodified: 
[debug]         Added: /home/cameron/.workspace/blog/src/main/scala/templates/Templates.scala, /home/cameron/.workspace/blog/src/main/scala/utils/Imports.scala, /home/cameron/.workspace/blog/src/main/scala/site/About.scala, /home/cameron/.workspace/blog/src/main/scala/site/Blog.scala, /home/cameron/.workspace/blog/src/main/scala/site/Index.scala
[debug]         Removed: 
[info] Formatting 5 Scala sources...
[debug] Adding repositories [https://repo1.maven.org/maven2/,file:////home/cameron/.sbt/preloaded/,https://oss.sonatype.org/content/repositories/snapshots]
[error] org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: /home/cameron/.workspace/blog/.scalafmt.conf
[error] Caused by: java.lang.reflect.InvocationTargetException
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[error]         at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
[error]         at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at fansi.ColorCategory.<init>(Fansi.scala:850)
[error]         at fansi.Color$.<init>(Fansi.scala:717)
[error]         at fansi.Color$.<clinit>(Fansi.scala)
[error]         at fansi.Attr$.<init>(Fansi.scala:623)
[error]         at fansi.Attr$.<clinit>(Fansi.scala)
[error]         at fansi.Str$.<init>(Fansi.scala:373)
[error]         at fansi.Str$.<clinit>(Fansi.scala)
[error]         at org.scalafmt.config.OptIn$.$anonfun$surface$1(OptIn.scala:86)
[error]         at pprint.TPrint$$anon$2.render(TPrint.scala:21)
[error]         at org.scalafmt.config.OptIn$.surface$lzycompute(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn$.surface(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn.<init>(OptIn.scala:82)
[error]         at org.scalafmt.config.ScalafmtConfig$.apply$default$4(ScalafmtConfig.scala:131)
[error]         at org.scalafmt.config.ScalafmtConfig$.<init>(ScalafmtConfig.scala:208)
[error]         at org.scalafmt.config.ScalafmtConfig$.<clinit>(ScalafmtConfig.scala)
[error]         at org.scalafmt.Scalafmt$.format$default$2(Scalafmt.scala:87)
[error]         at org.scalafmt.Scalafmt.format$default$2(Scalafmt.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]         at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
[error]         at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at fansi.ColorCategory.<init>(Fansi.scala:850)
[error]         at fansi.Color$.<init>(Fansi.scala:717)
[error]         at fansi.Color$.<clinit>(Fansi.scala)
[error]         at fansi.Attr$.<init>(Fansi.scala:623)
[error]         at fansi.Attr$.<clinit>(Fansi.scala)
[error]         at fansi.Str$.<init>(Fansi.scala:373)
[error]         at fansi.Str$.<clinit>(Fansi.scala)
[error]         at org.scalafmt.config.OptIn$.$anonfun$surface$1(OptIn.scala:86)
[error]         at pprint.TPrint$$anon$2.render(TPrint.scala:21)
[error]         at org.scalafmt.config.OptIn$.surface$lzycompute(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn$.surface(OptIn.scala:86)
[error]         at org.scalafmt.config.OptIn.<init>(OptIn.scala:82)
[error]         at org.scalafmt.config.ScalafmtConfig$.apply$default$4(ScalafmtConfig.scala:131)
[error]         at org.scalafmt.config.ScalafmtConfig$.<init>(ScalafmtConfig.scala:208)
[error]         at org.scalafmt.config.ScalafmtConfig$.<clinit>(ScalafmtConfig.scala)
[error]         at org.scalafmt.Scalafmt$.format$default$2(Scalafmt.scala:87)
[error]         at org.scalafmt.Scalafmt.format$default$2(Scalafmt.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at org.scalafmt.dynamic.utils.ReflectUtils$ClassReflectOps$.invokeStatic$extension(ReflectUtils.scala:34)
[error]         at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:31)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
[error]         at scala.util.Either.flatMap(Either.scala:341)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
[error]         at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:70)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:122)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:116)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:164)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1(ScalafmtPlugin.scala:149)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$formatSources$1$adapted(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$4(ScalafmtPlugin.scala:269)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3(ScalafmtPlugin.scala:268)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$3$adapted(ScalafmtPlugin.scala:263)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$trackSourcesAndConfig$1(ScalafmtPlugin.scala:272)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:274)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:137)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1(ScalafmtPlugin.scala:317)
[error]         at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$1$adapted(ScalafmtPlugin.scala:310)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$FailedToFormat: /home/cameron/.workspace/blog/.scalafmt.conf
</details>

**Comment by kitbellew** [comment]
mentioned as fixed in com-lihaoyi/PPrint#24.
