### ISSUE TITLE
Specify --mode diff when using plugin

### ISSUE THREAD

**Issue by alexklibisz** [scalameta/sbt-scalafmt#109]
Hi, we're using this plugin in our org and recently updated from 1.2.0 to the latest version.
This led to very large scalafmt diffs, and we'd prefer to catch up incrementally over time.
It seems that the scalafmt CLI lets you specify `--mode diff` which will only apply scalafmt to the files that are diffed against the main/master branch.
Is there a way to specify this flag in the plugin? 
If not, I'd be happy to try to contribute the change, but would appreciate some direction. 
For example, is the plugin the right place to put this? Maybe it actually belongs in the .scalafmt.conf file, in which case the change should occur in the main scalafmt repo?

**Comment by poslegm** [comment]
Hello! Sadly, there is a global problem with it.

Duplicated issue https://github.com/scalameta/sbt-scalafmt/issues/18, related issue: https://github.com/scalameta/sbt-scalafmt/issues/11

Code for handling `--diff` and another useful CLI flags is located in the [scalafmt-cli](https://github.com/scalameta/scalafmt/blob/d87c4eef6feac4303c17791bc50af3a812182264/scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala#L46-L73) module and cannot be accessed from any other place. Duplicating this code in the plugin doesn't seem like the best idea to me. In a good way we must extract useful options to another common module (`scalafmt-control`? `scalafmt-management`?) and depend on it in the CLI and in the plugin. But this requires a lot of effort to refactoring.

**Comment by alexklibisz** [comment]
@poslegm I see, thanks for the explanation. I have a follow up question: there are already some runner params that work from the scalafmt file, e.g. `runner.debug`. I figured maybe `runner.mode` would be a similar mechanism. Is the `runner` completely distinct from the `cli`?

**Comment by poslegm** [comment]
It's a name collision. `ScalafmtRunner` from CLI module reads files and pass it to formatter. `runner` from config describes formatter parameters (parsing dialect, max iterations count, verbose logging, etc)

**Comment by poslegm** [comment]
Yes! Thank you. I will try to use it in the plugin soon.
