### ISSUE TITLE
project.git = true seems to be ignored when using sbt-scalafmt

### ISSUE THREAD

**Issue by blast-hardcheese** [scalameta/sbt-scalafmt#11]
### Setup
```
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
```

### .scalafmt.conf:
```
project.git = true

style = defaultWithAlign

danglingParentheses        = true
maxColumn                  = 160
project.excludeFilters     = [".*\\.sbt"]
rewrite.rules              = [AsciiSortImports, RedundantBraces, RedundantParens]
spaces.inImportCurlyBraces = true
unindentTopLevelOperators  = true
```
### .gitignore
```
.DS_Store
target/

modules/sample*/target/
modules/sample*/src/main/scala/*
modules/sample*/src/main/scala/generated/*
!modules/sample*/src/main/scala/App.scala
!modules/sample*/src/main/scala/support
!modules/sample*/src/test/resources/

.idea
```

despite this, when running `scalafmtCheck`, I still get files that are explicitly ignored (under `modules/sample*/src/main/scala/generated`)

**Comment by poslegm** [comment]
@olafurpg @tanishiking 
I found that `project.git` flag handling [encapsulated](https://github.com/scalameta/scalafmt/blob/master/scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala#L205) in `CliOptions`. So it is scalafmt-cli specific feature yet (correct me if I am wrong). 

We can copy-paste that code into this project but it is not seems good decision. Can we make this code reusable (may be through scalafmt-dynamic package)?

Another problem with #18
