### ISSUE TITLE
Plugin missing for scala 2.11 and 2.13

### ISSUE THREAD

**Issue by cbcoutinho** [scalameta/sbt-scalafmt#113]
This plugin is only available for projects using scala 2.12. Others based on 2.11 or 2.13 result in the following resolver error because it isn't available via maven.

I don't see any available sbt-scalafmt plugin for 2.11 or 2.13 on [maven](https://repo1.maven.org/maven2/org/scalameta/), but I'm also not a regular java/scala dev so not sure if this is the right place to look.

```
[error] Error downloading org.scalameta:sbt-scalafmt;sbtVersion=1.0;scalaVersion=2.13:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /home/chris/.ivy2/local/org.scalameta/sbt-scalafmt/scala_2.13/sbt_1.0/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.13_1.0/2.4.0/sbt-scalafmt-2.4.0.pom
[error] Total time: 1 s, completed Jul 22, 2020 10:21:14 AM
```

**Comment by poslegm** [comment]
scalafmt plugin should not rely on Scala version of project. How do you add it into your `plugins.sbt`?

**Comment by cbcoutinho** [comment]
I have the following line in my `~/.sbt/1.0/plugins.sbt`
```sbt
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
```

**Comment by poslegm** [comment]
What happens if you add this line to `project/plugins.sbt`?

**Comment by cbcoutinho** [comment]
The same issue as the global plugin - It works if the scala version is
2.12.x, but not for 2.{11,13}.x

**Comment by poslegm** [comment]
It's strange. Can you please provide content of your `build.sbt`, `build.properties` and `plugins.sbt` files?

**Comment by cbcoutinho** [comment]
I think I found my mistake: my global plugin file was not in a `plugins` subdirectory

I had
```
~/.sbt/1.0/plugins.sbt
```
And should have been
```
~/.sbt/1.0/plugins/plugins.sbt
```
