### ISSUE TITLE
Error when no version specified in config

### ISSUE THREAD

**Issue by codan84** [scalameta/sbt-scalafmt#114]
According to docs it should use latest by default. The actual behaviour is an error when this value is missing in config.
```
[error] missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.5.2'.: /a/b/c/my-service/.scalafmt.conf
```

**Comment by poslegm** [comment]
Thank you for report. I will release version with fix soon

**Comment by eallovon** [comment]
Hello, 
This bug re-appeared in v2.4.4

I'm using sbt-scalafmt 
- with v2.4.2: I can run scalafmtCheck
- with v2.4.3: I can run scalafmtCheck
- with v2.4.4 (till 2.4.6): when I run scalafmtCheck I get the error:
  ```
[xucmgt] $ scalafmtCheck
[info] Checking 16 Scala sources...
[error] missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=3.1.1'.: /home/.../.scalafmt.conf
  ```
