### ISSUE TITLE
Getting warning message after upgrade to sbt 1.5.0 

### ISSUE THREAD

**Issue by JennyLeahy** [scalameta/sbt-scalafmt#137]
While upgrading to sbt 1.5.0, I got following warning: 
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: my_project / Test / scalafmtCheck

It's only a warning, but it would be nice not to see it.

**Comment by daddykotex** [comment]
Can you update your project build following the sbt update?

I don't know enough about your project to know when/why the warning is triggered, but if:

- it's when you do `my_project/test:scalafmtCheck`, then you should do `my_project/Test/scalafmtCheck`
- it's when you start sbt, then your build definition needs to be updated, i.e. `someSetting in scalafmtCheck := ...` needs to become `scalafmtCheck / someSetting := ...`
