### ISSUE TITLE
Don't format custom package with includePaths

### ISSUE THREAD

**Issue by paulo-coutinho** [scalameta/sbt-scalafmt#152]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.6
- **Integration**: Terminal direct
- **Configuration**:
```
version = 3.0.6
```

## Steps

Given code like this:
```scala
var name =               "test"
```

When I run scalafmt like this:

```bash
sbt scalafmtall
```

## Problem

Scalafmt formats code like this:
```scala
var name =               "test"
```

## Expectation

I would like the formatted output to look like this:
```scala
var name = "test"
```

## Notes

My file is not inside `src/main`, but inside `src/it`.

I already tried a lot of glob configurations:

```
project.includePaths = ["glob:**/src/it/scala/djinni/*.scala"]
project.includePaths = ["glob:**/*.scala"]
project.includePaths = ["glob:*.scala"]
project.includePaths = ["glob:**.scala"]
```

Nothing works.

Our repository:
https://github.com/cross-language-cpp/djinni-generator

**Comment by kitbellew** [comment]
@poslegm could it be that `IntegrationTest` is not included on this line:
https://github.com/scalameta/sbt-scalafmt/blob/master/plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L480

**Comment by kitbellew** [comment]
@paulo-coutinho can you try this with sbt-scalafmt-2.4.3+16-c6009e68-SNAPSHOT?

**Comment by sebarys** [comment]
I had similar issue and solved it by adding `scalafmtConfigSettings` (as described here https://scalameta.org/scalafmt/docs/installation.html#enable-integrationtest )
to sbt `Configuration` that is taking care of files that should be formatted e.g. in case of IntegrationTest config
```
inConfig(IntegrationTest)(org.scalafmt.sbt.ScalafmtPlugin.scalafmtConfigSettings)
```

**Comment by kitbellew** [comment]
@sebarys can you try if a recent build (like sbt-scalafmt-2.4.3+16-c6009e68-SNAPSHOT) solves the problem without explicit `inConfig(...)`

**Comment by paulo-coutinho** [comment]
Hi,

How can i use this version @kitbellew?

I tried:

```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.3+16-c6009e68-SNAPSHOT")
```

and

```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "sbt-scalafmt-2.4.3+16-c6009e68-SNAPSHOT")
```

Can you help me?

**Comment by kitbellew** [comment]
> How can i use this version @kitbellew?
> 
> Can you help me?

I don't know, unfortunately. I don't use sbt myself, and in maven it works. Maybe the repository is incorrect.

**Comment by kitbellew** [comment]
try 2.4.4, it should be published in a few minutes.

**Comment by paulo-coutinho** [comment]
Hi,

I tried version 2.4.4 and it worked without:

```
inConfig(IntegrationTest)(org.scalafmt.sbt.ScalafmtPlugin.scalafmtConfigSettings)
```

Thanks.
