### ISSUE TITLE
scalafmt sbt task with diff option

### ISSUE THREAD

**Issue by torkelrogstad** [scalameta/sbt-scalafmt#18]
Is it possible to invoke `sbt scalafmt`/`sbt test:scalafmt` with the `--diff` and `--diff-branch` options available in the CLI?

**Comment by poslegm** [comment]
@torkelrogstad Is this issue actual after incremental formatting introducing? Now sbt plugin can format only files changed after last compilation.

Scalafmt CLI needs git to format only last edited files but `sbt-scalafmt` has access to sbt cache.

**Comment by olafurpg** [comment]
I think this is still a desirable feature for people who are not using format on compile, I personally use `--diff` + format on save in the editor.

**Comment by torkelrogstad** [comment]
The use case here is getting better diffs for writing patches/PRs. If I'm changing a file I would like for it to be formatted, whereas files I don't touch shouldn't end up in the PR
