### ISSUE TITLE
Using `project.git` now  causes no files to be formatted

### ISSUE THREAD

**Issue by ckipp01** [scalameta/sbt-scalafmt#180]
I believe there was a regression introduced with the recent changes to the take into account the `project.git` setting. I can a reproduction repo [here](https://github.com/ckipp01/sbt-scalafmt-issue) that you can just clone and run `sbt scalafmtAll`.

### What happens

I have a single file that looks like this:

```
object Main extends App {
  
        println("Hello, World!"         )
}
```

I have a config that looks like this:

```
version                                    = 3.2.1
project.git                                = true
runner.dialect                             = scala213
```

When I run `sbt. scalafmtAll` it does nothing. There are no changes to the code above.

If I then remove the `project.git` setting, it formats correctly.

## Expectation

I'd expect this to format my file as there seems to be nothing in my git ignore that would prohibit this:

```
target/
metals.sbt
.metals/
.bloop/
.bsp/
```

Also note that with this same setup, trigging a format from Metals on the same file does format the file.

**Comment by kitbellew** [comment]
@ckipp01 i am sorry, i can't reproduce. checked out your repo (thank you for going to these lengths):
```
$ pwd
<HOME>/dev/code/sbt-scalafmt-issue

$ sbt scalafmtAll
[info] welcome to sbt 1.5.5 (GraalVM Community Java 11.0.11)
[info] loading global plugins from <HOME>/.sbt/1.0/plugins
[info] loading settings for project sbt-scalafmt-issue-build from plugins.sbt ...
[info] loading project definition from <HOME>/dev/code/sbt-scalafmt-issue/project
[info] loading settings for project sbt-scalafmt-issue from build.sbt ...
[info] set current project to hello-world (in build file:<HOME>/dev/code/sbt-scalafmt-issue/)
[info] Formatting 1 Scala sources...
[success] Total time: 2 s, completed Dec 7, 2021, 6:23:08 PM

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/main/scala/Main.scala

no changes added to commit (use "git add" and/or "git commit -a")

$ git diff
diff --git a/src/main/scala/Main.scala b/src/main/scala/Main.scala
index df9e853..d315ccc 100644
--- a/src/main/scala/Main.scala
+++ b/src/main/scala/Main.scala
@@ -1,4 +1,4 @@
 object Main extends App {
-  
-        println("Hello, World!"         )
+
+  println("Hello, World!")
 }
```

is it possible there's a problem with running a `git` process within `sbt`?

**Comment by ckipp01** [comment]
I went back and tried again today... and it works. No idea what was going on when I tried this, but thanks for looking into it and sorry for the noise!

**Comment by kitbellew** [comment]
@ckipp01 did you have a project with multiple source directories (possibly a cross-project build with `shared` and platform-specific)?

**Comment by ckipp01** [comment]
> @ckipp01 did you have a project with multiple source directories (possibly a cross-project build with `shared` and platform-specific)?

Hey @kitbellew when I first came across this issue it was just a single module project. But since then I've never been able to reproduce. So it seems it was jus something odd for me locally at the time.
