### ISSUE TITLE
Diff mode doesn't work with remote branch

### ISSUE THREAD

**Issue by eliax1996** [scalameta/sbt-scalafmt#181]
I tried to check the formatting only of the files involved in modifications to the git origin.
What I want to achieve was to enforce formatting only for the files edited in the current feature branch by checking which files to edit based on the remote `develop` branch.
But, if in my project if I set in the sbt variable as follows:

```scala
ThisBuild / scalafmtFilter := "diff-ref=origin/develop"
```

and I launch `sbt scalafmtCheck` or `sbt scalafmtCheck` the result is:

```bash
[success] Total time: 1 s, completed Dec 6, 2021, 4:48:48 PM
```

I suppose that all the files are simply ignored.
If for example, I set:

```scala
ThisBuild / scalafmtFilter := "diff-ref=OMG/myFancyNotExistingBranch"
```

the output is the same.

The modifications are present, if in the same root dir I execute:
```bash
 git diff --name-only --diff-filter=d origin/develop
```

the result is:

```
build.sbt
my-scala-module/src/main/scala/com/example/X.scala
project/plugins.sbt
```

and if I manually launch `scalafmt` by command line with the following command:
```bash
scalafmt --config .scalafmt.conf --diff-branch origin/develop --test
```

The test doesn't pass because the files don't respect the formatting (while with the plugin the files pass the check).

**Comment by kitbellew** [comment]
@eliax1996 can you create a small repo which demonstrates the error? there was a similar issue #180 but it somehow went away...

**Comment by kitbellew** [comment]
can't reproduce. please re-open if you can help recreate the problem.
