### ISSUE TITLE
Bumping from 2.4.4 to 2.4.5, scalafmtCheckAll ignores badly formatted files if git is not setup and config says otherwise

### ISSUE THREAD

**Issue by daddykotex** [scalameta/sbt-scalafmt#189]
Hi,

Thanks for sbt-scalafmt. We use it extensively. I create this issue mostly for documentation purposes because I guess we won't be the only to have this issue. We have an in-house sbt plugin that uses sbt-scalafmt. Bumping from 2.4.4 to 2.4.5, one of our test started to fail.

The test contains one source file that is badly formatted. When sbt runs the test, it copies everything into a new directory, where git is not setup. I understand that's why `scalafmtCheckAll` does not fail anymore: git is not setup, but our config says git is.

Looking at the changelog, I can see https://github.com/scalameta/sbt-scalafmt/pull/172 could have an effect on this.

I have a solution and it's fine for me.

**Comment by kitbellew** [comment]
@daddykotex should you remove `project.git = true` if git is not set up and thus not used? the only purpose of that setting is use git to determine which files should be formatted.

**Comment by daddykotex** [comment]
I understand that, and git is used in all of our projects. The issue only
happen in this sbt-plugin test where the project directory is copied
outside of the project directory (into a temporary folder) to run the test.

It's similar to what you have in this project's test suite (p17) where you
init git before running the test.

Now, I could probably update the config but its generated and all of our
projects use git, so changing the behavior just for that test seems too
much. Instead, I run `$ exec git init` and setup git in that temporary
directory, within the test itself.

As I said, this issue can be closed, my goal was only to get ot out there
is someone has a similar issue.

**Comment by kitbellew** [comment]
@daddykotex understood, thank you. is there a recommended solution?

**Comment by kitbellew** [comment]
also, it's possible that the next version will work. in #183, git is within Try and falls back to no filtering.

**Comment by daddykotex** [comment]
> @daddykotex understood, thank you. is there a recommended solution?

We have a sbt-test, that runs in a layout like this:
```
.
├── build.sbt
├── p1
│   └── src
│       └── main
│           └── scala
│               └── Hello.scala # this file is not formatted properly
├── project
│   ├── build.properties
│   ├── plugins.sbt
│   └── project
└── test
```

I updated the `test` file with the following diff:
```
diff --git a/src/sbt-test/sbt-company/tools/test b/src/sbt-test/sbt-company/tools/test
index 1047a45..6f9d5c7 100644
--- a/src/sbt-test/sbt-company/tools/test
+++ b/src/sbt-test/sbt-company/tools/test
@@ -4,6 +4,12 @@
 > generateScalafmtConf
 $ exists .scalafmt.conf

+# we set up git, and commit all the files
+# otherwise, scalafmt wont check them (starting 2.4.5)
+# if project.git = true
+$ exec git init -b main
+$ exec git add .
+$ exec git commit -m "init commit"
+
 # fails because the formatting is in error
 -> p1/scalafmtCheckAll
```

If the generated config did not contain `project.git = true`, I assume no problem would have happened. But the configuration contains it because all of our project are on git. So instead of adding logic to update the config, I made sure that, during this particular test, we setup git before running scalafmt.
