### ISSUE TITLE
`shared/` sources for cross-platform projects ignored in 2.4.5

### ISSUE THREAD

**Issue by armanbilge** [scalameta/sbt-scalafmt#190]
It seems after bumping from 2.4.4 to 2.4.5 sources in `shared/` folders (used for JVM/JS cross-platform projects) are being ignored. See this PR for a reproduction:
- https://github.com/typelevel/feral/pull/100

Related to https://github.com/scalameta/sbt-scalafmt/issues/189?

**Comment by kitbellew** [comment]
do you also copy files outside of git tree? if you run sbt locally, does it work? if you run scalafmt binary, not via sbt, does it work?

**Comment by armanbilge** [comment]
> do you also copy files outside of git tree? if you run sbt locally, does it work?

No, I don't copy files out of the git tree.

> if you run scalafmt binary, not via sbt, does it work?

I realized the issue after running scalafmt via the metals menu option, and realizing it was formatting files that sbt was ignoring.

**Comment by kitbellew** [comment]
still, if you run the scalafmt binary (not metals or any other integration but the actual CLI), does it work? https://scalameta.org/scalafmt/docs/installation.html#cli

**Comment by armanbilge** [comment]
Thanks for the pointer. Yes, running the `scalafmt` binary directly also works.

**Comment by armanbilge** [comment]
Thanks for fixing! ❤️
