### ISSUE TITLE
"fatal: bad revision 'main'" in Jenkins after updating from 2.4.5 to 2.4.6 with scalafmtFilter diff-ref

### ISSUE THREAD

**Issue by alexklibisz** [scalameta/sbt-scalafmt#205]
Hi, I'm trying out the new scalafmtFilter setting, set like this:

```scala
scalafmtFilter.withRank(KeyRanks.Invisible) := "diff-ref=main",
```

Then I run:

```bash
sbt scalafmtCheckAll
```

When I run this on 2.4.5, it works as expected. When I run on 2.4.6, it fails with the following error:

```bash
[error] scalafmt: format all files; [git diff main] (my-project): Failed to run command git diff --name-only --diff-filter=d main -- my-project/src/main/scala my-project/src/main/scala-2.13 my-project/src/main/scala-2 my-project/src/main/java. Error:
[error] > fatal: bad revision 'main'
```

Both versions work locally. This error only happens in Jenkins, which I suppose might be using a different clone/checkout strategy than my local repo.

LMK if you have any more information or any ideas about where to look to patch this. Thanks!

**Comment by kitbellew** [comment]
since in Jenkins no files would likely be changed, you will end up formatting nothing. what are you trying to accomplish?

as to the error: the plugin executes git, reports the error.

**Comment by kitbellew** [comment]
also, you can set logging to debug and get more insight.

**Comment by alexklibisz** [comment]
> since in Jenkins no files would likely be changed, you will end up formatting nothing. what are you trying to accomplish?

I'm running `scalafmtCheckAll`. I want to check if all files that have changed with respect to the `main` branch are formatted. If any file has changed with respect to `main`, the `sbt scalafmtCheckAll` command should exit with a failure.

> as to the error: the plugin executes git, reports the error.

Did something change in how it executes git between 2.4.5 and 2.4.6? Again, 2.4.5 works fine, 2.4.6 fails.

> also, you can set logging to debug and get more insight.

I can try that out.

**Comment by kitbellew** [comment]
> > since in Jenkins no files would likely be changed, you will end up formatting nothing. what are you trying to accomplish?
> 
> I'm running `scalafmtCheckAll`. I want to check if all files that have changed with respect to the `main` branch are formatted. If any file has changed with respect to `main`, the `sbt scalafmtCheckAll` command should exit with a failure.

perhaps you want `origin/main`, not `main`?

> Did something change in how it executes git between 2.4.5 and 2.4.6? Again, 2.4.5 works fine, 2.4.6 fails.

Yes; earlier, any git failures were silently ignored and now they are explicitly reported. It's likely that it didn't work with 2.4.5 but you didn't know that.

**Comment by alexklibisz** [comment]
> It's likely that it didn't work with 2.4.5 but you didn't know that.

I think that's what was happening.

> perhaps you want origin/main, not main

Adding the `origin/` prefix seems to have fixed the issue. Thanks!
