### ISSUE TITLE
 Error when no version specified in config

### ISSUE THREAD

**Issue by eallovon** [scalameta/sbt-scalafmt#211]
Hello, 
There is a regression since v2.4.4, bug #114 was re-introduced (or doc was not updated :-)).

It was re-introduced by commit 560d8519038f3d9281098a36e9273aad8288b0db

I'm using sbt-scalafmt I don't have the version in .scalafmt.conf and as said [in the doc](https://scalameta.org/scalafmt/docs/installation.html#sbt) it should use the latest version 
- with v2.4.2: I can run scalafmtCheck
- with v2.4.3: I can run scalafmtCheck
- with v2.4.4 (till 2.4.6): when I run scalafmtCheck I get the error:
```
[xucmgt] $ scalafmtCheck
[info] Checking 16 Scala sources...
[error] missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=3.1.1'.: /home/.../.scalafmt.conf
```

**Comment by kitbellew** [comment]
we will update the doc. explicit version and dialect are now mandatory:
https://scalameta.org/scalafmt/docs/configuration.html#version
