### ISSUE TITLE
Does this work with ammonite scripts?

### ISSUE THREAD

**Issue by mcanlas** [scalameta/sbt-scalafmt#245]
Is running `scalafmt` in `sbt` expected to touch ammonite scripts in the same repo/project? I can't get it to work for me and I'm unsure what preconditions I'm missing. Googling for `ammonite` seems to imply that `scalafmt` does work but what about via `sbt`?

**Comment by ckipp01** [comment]
> Is running scalafmt in sbt expected to touch ammonite scripts in the same repo/project?

I don't believe it will. Since it's an sbt project it'll probably only touch sources that sbt knows about, and since Ammonite scripts are standalone from the sbt project, sbt won't know about it.

That being said, if you'd instead use `scalafmt` cli on  your project I believe it would.
