### ISSUE TITLE
scalaFmt is extremely slow

### ISSUE THREAD

**Issue by jrudolph** [scalameta/sbt-scalafmt#25]
In some way, it's a duplicate of #9. However, even if you take the use case of "format of compile" (which is a valid use case for some users) out of the picture, it's still almost too slow to be usable in bigger projects. E.g. akka recently switched to scalafmt and reformatting the whole project takes ~200s. Just validating the formatting for PR validation adds takes several minutes on our build server.

I did a quick profiling run which shows very weird results. From what I can see, one reason might be that sbt-scalafmt's class loader magic prevents efficient JIT compilation of the formatter itself.

**Comment by olafurpg** [comment]
Thanks for reporting! It might be that the switch to dynamic classloading resulted in a large slowdown. It's worth looking into, I believe we cache the classloader but maybe I overlooked something. I personally don't use the sbt plugin and don't recommend "format on compile".

The way I use Scalafmt is "format on save" in the editor and `./scalafmt --diff` from the cli before opening pull requests.

Scalafmt itself is ~6x slower than Scalariform (see https://scalameta.org/scalafmt/docs/known-issues.html#performance) when I measured it a few years ago and I'm afraid there's not much to do about it with the current implementation. The pretty-printer in https://github.com/scalacenter/scala-syntax could replace the current printer and it was ~6-7x faster on basic benchmarks. There is nobody working on completing that project however so it's difficult to estimate when/if that becomes usable.

**Comment by olafurpg** [comment]
I ran `scalafmt` on all sources in the Akka build (2k source files) with my MacBook and it took ~110-130 seconds

```
$ time scalafmt
scalafmt  445.08s user 6.65s system 602% cpu 1:14.99 total
scalafmt  506.68s user 7.12s system 579% cpu 1:28.65 total
```

I'm not sure why it's slower in sbt, maybe it's not as parallel as the cli 🤔 

My experience using Scalafmt is that most PRs only change a few files so running `./scalafmt --diff` normally completes in <5s even for large PRs, which is still tragically slow but manageable. With format on compile you need to format everything on every checkout, which I agree is unacceptable if that takes ~200s in a large build with 2k Scala source files.
