### ISSUE TITLE
Possibility to make new version with fix of  #290 available as binary

### ISSUE THREAD

**Issue by PashoQ** [scalameta/sbt-scalafmt#295]
Could you please make a new release with the fix introduced in #290?

**Comment by kitbellew** [comment]
why is that a requirement? the problem was with scalafmt 3.7.16, and there was no "fix" in #290. if you use 3.7.17, your current sbt-scalafmt should work just fine.

**Comment by PashoQ** [comment]
Sorry, was missing the info about that it works with 3.7.17. It was failing with 3.7.16. 
I am sorry for the confusion, thank you very much for your work.
