### ISSUE TITLE
Allow formatting without a .scalafmt.conf?

### ISSUE THREAD

**Issue by bergmark** [scalameta/sbt-scalafmt#32]
The documentation for sharing a scalafmt config between projects suggests:

```scala
    SettingKey[Unit]("scalafmtGenerateConfig") :=
      IO.write(
        // writes to file once when build is loaded
        file(".scalafmt.conf"),
        "maxColumn = 100".stripMargin.getBytes("UTF-8")
      )
```

What about allowing usage of `--config-str <value>` so a file doesn't need to be written?

**Comment by olafurpg** [comment]
Thanks for reporting! I'm afraid `--config-str <value>` would be problematic because the .scalafmt.conf file is needed for other integrations like the IntelliJ plugin and Metals to use the same configuration as the build.
