### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by akaczynski** [scalameta/sbt-scalafmt#35]
Hi,
my question is about license of the project. While I can see "license name" entry in the ivy xml for jars which refers to Apache2.0 I can not see something like that for the source code (while scalafmt projects has). Is there any particulars purpose in that? Does it mean that binary is under Apache and source code not?

**Comment by poslegm** [comment]
@akaczynski Source code is under Apache 2.0 license. I added it to the repo.

**Comment by akaczynski** [comment]
thanks, I think that is clear right now 👍
