### ISSUE TITLE
It is unclear what scalafmt version is supported

### ISSUE THREAD

**Issue by exoego** [scalameta/sbt-scalafmt#37]
# Problem
I think it is unclear which scalafmt `version` in `.scalafmt.conf` the sbt-scalafmt supports.
E.g. `version = 2.0.0-RC7` for `addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.1")`.

This makes it difficult to implement automatic update `sbt-scalafmt` in Scala Steward https://github.com/fthomas/scala-steward/issues/625, since a PR to update `sbt-scalafmt` may be broken if `version` in `.scalafmt.conf` is not updated together.

This issus maybe applicable to humans too.
I could not find these version relationship in document...

# Expectation

### Option 1 (preferreable). Use same version in `scalafmt` and `sbt-scalafmt`.

From UX POV, I think this is most straightforward for users and bots like Scala Steward.
However, a caveat is that `scalafmt` and `sbt-scalafmt` should release newer version at same time even if no changes in one side.
   
### Option 2. Include `scalafmt` version in `sbt-scalafmt` version.

Let's say if `scalafmt` is `2.1.0`, `sbt-scalafmt` may be `2.0.10-2.1.0`.
This may be tricky for Scala Steward and humans, but release timing do not need synchronization.

**Comment by poslegm** [comment]
@exoego Hello! Do you have any errors when using sbt-scalafmt v2.0.1 with scalafmt `version` in config 2.0.0-RC7? I can't reproduce it, plugin fetches specified formatter version correct.

So there is no strict relation between version in `.scalafmt.conf` and plugin version. Or did I get something wrong?

**Comment by exoego** [comment]
Ah, you are totally correct !!
`version=2.0.0-RC7` or even `version=2.0.0` works fine with `sbt-scalafmt 2.0.2`.
I did not know `sbt-scalafmt` fetches the specified formtter.
So `version` in `.scalafmt.conf` can be updated separately with `sbt-scalafmt`.

Closing since this is my misunderstanding.
Thanks !!
