### ISSUE TITLE
java.util.regex.PatternSyntaxException: Unclosed group near index 9 [error] (target\)

### ISSUE THREAD

**Issue by OlegYch** [scalameta/sbt-scalafmt#5]
running sbt-scalafmt 1.6.0-RC3 on windows
executing either `scalafmt` or `scalafmSbt`

**Comment by OlegYch** [comment]
why are you guys passing raw strings to regex? what if filename contains ? or [
noticed same issue in scalafix https://github.com/scalacenter/scalafix/issues/583

**Comment by olafurpg** [comment]
Thanks for reporting. This was a piece of code I wrote in my early days and
got copy pasted around. The correct solution I believe is to use nio
PathMatcher and that's what scalafix in current master does. PRs welcome!

**Comment by exoego** [comment]
I can format files when using `"sbt-scalafmt" % "2.0.2"` on Windows.
Perhaps this issue is resolved somewhere after `1.6.0-RC3` ?

**Comment by poslegm** [comment]
I can't reproduce it with `sbt-scalafmt` v2.2.0 and `scalafmt` v2.2.0. Feel free to reopen this issue  if I missed anything.
