### ISSUE TITLE
[2.0.4+] Managed sources from meta builds should not be formatted/checked

### ISSUE THREAD

**Issue by bjaglin** [scalameta/sbt-scalafmt#51]
### Steps to reproduce

Set up a basic project where the meta build has managed sources (in this case, a dummy twirl Scala template)

`.scalafmt.conf`
```
version = 2.0.0
```

`project/plugins.sbt`
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.6")
```

`project/build.sbt`
```
lazy val root = (project in file("."))
  .enablePlugins(SbtTwirl)
```

`project/src/main/twirl/template.scala.txt`
```
```

`project/project/plugins.sbt`
```
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.4.2")
```

### Actual
```
bjaglin@x1:/tmp/sbt-project$ sbt scalafmtSbtCheck
[info] Loading settings for project global-plugins from idea.sbt,build.sbt ...
[info] Loading global plugins from /home/bjaglin/.sbt/1.0/plugins
[info] Loading settings for project sbt-project-build-build from plugins.sbt ...
[info] Loading project definition from /tmp/sbt-project/project/project
[info] Loading settings for project root from plugins.sbt,build.sbt ...
[info] Loading project definition from /tmp/sbt-project/project
[info] Set current project to sbt-project (in build file:/tmp/sbt-project/)
[info] Checking 3 Scala sources...
[info] Checking 1 Scala sources...
[warn] /tmp/sbt-project/project/target/scala-2.12/sbt-1.0/twirl/main/txt/template.template.scala isn't formatted properly!
[error] 1 files must be formatted
[error] (Compile / scalafmtSbtCheck) 1 files must be formatted
[error] Total time: 2 s, completed Sep 30, 2019, 10:23:57 PM
```

### Expected
`sbt scalafmtSbtCheck` succeeds - managed sources are ignored.

### Real-world scenario
[Akka-gRPC](https://github.com/akka/akka-grpc) supports custom code generation from protobuf files.

**Comment by bjaglin** [comment]
I can't reproduce this with `2.0.3`, but I can with `2.0.4`, so it seems that https://github.com/scalameta/sbt-scalafmt/pull/46/files#diff-0a93a8dada6761d84102326db6ef7b1fR271-R274 changed the behavior somehow.

**Comment by bjaglin** [comment]
I can't think of any "proper way" to solve this - assuming it's considered a problem obviously, but I think it is confusing as other non-sbt managed sources are ignored.

Ideas:
* We could blacklist paths for the default `managedSources` instead of simply collecting all `*.scala` files, but we cannot know if they have been customized (AFAIK there is no way to access settings values across meta-builds)
* We can expose a filtering glob so that users can explicitly exclude the managed sources (or something else?) from the meta lookups, which might be acceptable as this is quite an advanced use-case anyway, so anyone facing this probably has a good understanding of sbt.

**Comment by bjaglin** [comment]
@poslegm do you have any idea/preference regarding how to handle this? I'd be happy to work on a PR if we can agree upfront.

**Comment by poslegm** [comment]
@bjaglin I will be happy to merge your PR 😄 

Helpful link is https://github.com/scalameta/scalafmt/issues/417. Scalafmt should ignore all target directory content.

I think about glob filter which will except files with `.../target/...` in path, but it can break code with package name `target` (someone writes a code like that, right?).

So

**Comment by poslegm** [comment]
Also https://github.com/scalameta/sbt-scalafmt/issues/11 can help with it. Managed sources just not indexed into git 🤷‍♂

**Comment by bjaglin** [comment]
Thanks for your feedback @poslegm! Great lookup, this is clearly an encore of https://github.com/scalameta/scalafmt/issues/417! And indeed, #11 would also be a way to workaround this, but I understand it's not trivial. I think we can explore https://github.com/scalameta/sbt-scalafmt/pull/54 as a first step!
