### ISSUE TITLE
Introduce scala-steward

### ISSUE THREAD

**Issue by tanishiking** [scalameta/sbt-scalafmt#53]
@scala-steward is a bot that creates PRs to update the dependencies, which is tried and trusted by a bunch of scala projects https://github.com/scala-steward-org/repos/blob/master/repos.md
It must be helpful for us to update dependencies 👍 

Since sbt-scalafmt doesn't have so many dependencies, I think we can manage the PRs from scala-steward easily. (probably, scalameta/scalafmt needs to organize the dependencies(remove unused dependencies and bump dependencies by hand) before introducing scala-steward)

What do you think about this? @olafurpg @poslegm

**Comment by poslegm** [comment]
It's definitely a good idea 👍

**Comment by tanishiking** [comment]
Opened PR https://github.com/scala-steward-org/repos/pull/33

**Comment by tanishiking** [comment]
scala-steward is working https://github.com/scalameta/sbt-scalafmt/pull/58 😄
