### ISSUE TITLE
sbt-scalafmt doesn't configure ScalafmtDynamicDownloader in order for sbt.override.build.repos to be respected

### ISSUE THREAD

**Issue by sideeffffect** [scalameta/sbt-scalafmt#62]
If you try to use `sbt-scalafmt` in a CI behind a firewall, with only Nexus/Artifactory-like mirror to `repo1.maven.org`, etc, `ScalafmtDynamicDownloader` won't be able to resolve `scalafmt`, because `repo1.maven.org` is not directly accessible, and the build will fail. Even if you setup sbt with `sbt.repository.config` and `sbt.override.build.repos=true`

sbt-scalafmt should configure ScalafmtDynamicDownloader in order for `sbt.override.build.repos` to be respected.

**Comment by poslegm** [comment]
Related issue https://github.com/scalameta/scalafmt/issues/1521

**Comment by milanvdm** [comment]
We have the same issue on our CI environment with a mirror artifactory. It pulls in the plugin correctly but the moment it tries to format, it hangs for a long time to error that it cannot resolve scalafmt version.

**Comment by tomasherman** [comment]
#87 fixed the issue for us 🎉

**Comment by Krever** [comment]
@tomasherman Do you have credentials required by your repository? In our case the repository is properly overridden but credentials are not being used.

**Comment by nikoplusx** [comment]
I am using sbt 1.5.1 and this error still occurs
