### ISSUE TITLE
`scalafmtOnCompile` takes too long

### ISSUE THREAD

**Issue by kailuowang** [scalameta/sbt-scalafmt#9]
Right now if we turn this on, it causes a 5-10 second overhead when compiling Cats.  I got the impression it's checking all files in the project rather than incremental. Is this true? If so is it something that can be improved?

**Comment by olafurpg** [comment]
Thanks for reporting! I thought the scalafmt task had been made incremental in https://github.com/scalameta/scalafmt/pull/1136 but it seems it still checksums all files on every run which may still be significant time for larger projects. I am sure this can be improved, I haven't tried myself but the `compile` task returns an analysis data structure that contains timestamps and filepaths that maybe can be used to make it more performant.

Contributions are welcome! I personally don't use or even recommend `scalafmtOnCompile`, this functionality was contributed externally.

**Comment by kailuowang** [comment]
Thanks @olafurpg . Peronally I don't prefer format on compile either, but I thought it less evil than requiring a manual step. We are considering git pre-commit hook but the addition of a pre-commit hook is still a manual step. Do you happen to know a fully automated way to reformat of the code?

**Comment by dwijnand** [comment]
Fixed by #13, which shipped in sbt-scalafmt 2.0.0-RC5?

**Comment by poslegm** [comment]
I find it acceptable to close this issue after incremental formatting introduction. Further perfomance problems and proposals can be documented as separate issues.
